### ISSUE TITLE
no matches for kind Trigger in version "eventing.knative.dev/v1beta1"

### ISSUE THREAD

**Issue by rbaumgar** [openshift-integration/camel-k-example-knative#13]
I have installed on my OpenShift 4.8 following operator
- Camel-k 1.4.0
- Serverless 1.17.0: servering + eventing

now when I run
$ kamel run --name simple-predictor -p predictor.name=simple Predictor.java

Cannot reconcile Integration simple-predictor: error executing post actions: error during create resource: &{{Trigger eventing.knative.dev/v1beta1} {default-simple-predictor-marketbtcusdt  camel-knative    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[camel.apache.org/generation:1 camel.apache.org/integration:simple-predictor] map[] [{camel.apache.org/v1 Integration simple-predictor 68383c07-37bf-4397-83fc-af53d4426f83 0xc0051d07b7 0xc0051d07b8}] []  []} {default 0xc005477ba8 {0xc004260a40 /events/market.btc.usdt} <nil>} {{0 [] map[]} }}: no matches for kind "Trigger" in version "eventing.knative.dev/v1beta1"

**Comment by christophd** [comment]
This is because of a breaking change in Serverless 1.16 -> 1.17 

Please update your Camel K operator

**Comment by rbaumgar** [comment]
I have already installed
```
  build:
    baseImage: 'registry.access.redhat.com/ubi8/openjdk-11:1.3'
    buildStrategy: routine
    maven:
      localRepository: /tmp/artifacts/m2
      settings:
        configMapKeyRef:
          key: settings.xml
          name: camel-k-maven-settings
      timeout: 3m45s
    persistentVolumeClaim: camel-k
    publishStrategy: S2I
    runtimeVersion: 1.7.1.fuse-800025-redhat-00001
    timeout: 5m0s
  cluster: OpenShift
  kamelet:
    repositories:
      - uri: none
  phase: Ready
  version: 1.4.2
```
currently no problems
